package(
    default_visibility = ["//visibility:public"],
)

cc_library(
    name = "thread_pool",
    srcs = [
        "thread_pool.cc",
    ],
    hdrs = [
        "thread_pool.h",
    ],
    deps = [
        "@com_google_highway//:thread_pool",
    ],
)
