package(
    default_visibility = ["//visibility:public"],
)

cc_library(
    name = "meta",
    hdrs = [
        "exception.h",
        "function.h",
        "type_traits.h",
    ],
    deps = [
        "//rapidudf/arena",
        "//rapidudf/log",
    ],
)
