package(
    default_visibility = ["//visibility:public"],
)

cc_library(
    name = "arena",
    srcs = [
        "leveldb_arena.cc",
    ],
    hdrs = [
        "arena.h",
        "leveldb_arena.h",
    ],
    deps = [
    ],
)
