package(
    default_visibility = ["//visibility:public"],
)

cc_library(
    name = "arena",
    srcs = [
    ],
    hdrs = [
        "arena.h",
    ],
    deps = [
        "@com_google_protobuf//:protobuf",
    ],
)
