package(
    default_visibility = ["//visibility:public"],
)

cc_library(
    name = "lru_cache",
    hdrs = [
        "lru_cache.h",
    ],
    deps = [
        "@com_google_absl//absl/container:flat_hash_map",
    ],
)
