package(
    default_visibility = ["//visibility:public"],
)

cc_library(
    name = "rapidudf",
    hdrs = [
        "rapidudf.h",
    ],
    deps = [
        "//rapidudf/compiler",
        "//rapidudf/reflect",
    ],
)
