package(
    default_visibility = ["//visibility:public"],
)

cc_library(
    name = "rapidudf",
    hdrs = [
        "rapidudf.h",
        "version.h",
    ],
    deps = [
        "//rapidudf/compiler",
        "//rapidudf/reflect",
        "//rapidudf/types:dyn_object_impl",
        "//rapidudf/vector:table",
    ],
)
