config_setting(
    name = "without_fbs",
    values = {
        "define": "without_fbs=1",
    },
)

config_setting(
    name = "without_pb",
    values = {
        "define": "without_pb=1",
    },
)
