package(
    default_visibility = ["//visibility:public"],
)

cc_library(
    name = "eval_engine",
    srcs = ["eval_engine.cc"],
    hdrs = [
        "eval_engine.h",
    ],
    deps = [
        "//rapidudf/common:lru_cache",
        "//rapidudf/compiler",
    ],
)
